name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What is the current issue or limitation?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see.
    validations:
      required: true
  - type: checkboxes
    id: impact
    attributes:
      label: User Impact
      options:
        - label: This improves performance
        - label: This improves UX
        - label: This is a critical security fix
